server:
  port: 8080
spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_NAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email

cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    s3:
      bucket: bbangjoa-bucket
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

logging:
  level:
    com.sweetievegan: debug

jwt:
#  secret: ${JWT_SECRET}
  issuer: ${JWT_ISSUER}
  secret_key: ${JWT_SECRET_KEY}